### ISSUE TITLE
Failure in appSyncTransformer.grantPrivate()

### ISSUE THREAD

**Issue by mciobanu** [kcwinner/cdk-appsync-transformer#369]
Hello,

I've been trying for several hours to get `appSyncTransformer.grantPrivate()` to work, and I still have no clear idea what's going on, but I tend to think it's a bug.

What happens is this: when I try to use `appSyncTransformer.grantPrivate()`, I get this error: `[MainInfrastructureStack/test-function/ServiceRole/DefaultPolicy] A PolicyStatement used in an identity-based policy must specify at least one resource.`

At first I tried to set policies or work around the issue in some other ways, but nothing worked.

Then I downloaded the *cdk-appsync-transformer* sources and the tests worked (well, except for *"Can Set Custom Directory"*, which couldn't find a file, but I only cared about *"Grant Access To Public/Private Fields"*).

This led me to believe that the issue must be with the package versions, so I tried to make adjustments, then copied the test code, but nothing helped.

Eventually I copied over my failing stack to the place where I had the *cdk-appsync-transformer* sources, made some adjustments to *package.json* and *tsconfig.json*, and added *cdk.json*, to also build my stack and to stop overwriting files, and now I'm in the situation where `npx tsc && cdk synth` fails, but `npm run test` succeeds. I run them in the same folder.

Here's the stack:
```
import * as cdk from '@aws-cdk/core';
import {AuthorizationType, UserPoolDefaultAction} from '@aws-cdk/aws-appsync';
import {UserPool, UserPoolClient} from '@aws-cdk/aws-cognito';
import {Runtime, Code, Function} from '@aws-cdk/aws-lambda';
import {AppSyncTransformer} from 'cdk-appsync-transformer';

export class TroubleshootStack extends cdk.Stack {
    constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
        super(scope, id, props);

        const stack = this;

        const userPool = new UserPool(stack, 'test-userpool');
        const userPoolClient = new UserPoolClient(stack, 'test-userpool-client', {
            userPool,
        });

        const appSyncTransformer = new AppSyncTransformer(stack, 'test-transformer', {
            schemaPath: 'graphql/schema.graphql',
            apiName: 'grant-test-api',
            authorizationConfig: {
                defaultAuthorization: {
                    authorizationType: AuthorizationType.USER_POOL,
                    userPoolConfig: {
                        userPool,
                        appIdClientRegex: userPoolClient.userPoolClientId,
                        defaultAction: UserPoolDefaultAction.ALLOW,
                    },
                },
            },
        });

        // We don't really need this to work
        const testPrivateFunction = new Function(stack, 'test-function', {
            runtime: Runtime.NODEJS_12_X,
            code: Code.fromInline('export function handler() { }'),
            handler: 'handler',
        });

        appSyncTransformer.grantPrivate(testPrivateFunction); // this triggers [MainInfrastructureStack/test-function/ServiceRole/DefaultPolicy] A PolicyStatement used in an identity-based policy must specify at least one resource.
        // removing grantPrivate() makes the build succeed
    }
}
```
So, am I doing something wrong or is this really a bug?

**Comment by mciobanu** [comment]
I got it working. I didn't realize the schema was important when calling `grantPrivate()`, and initially my schema didn't have any IAM authorization.

Could this be tested explicitly, to generate a more meaningful error message? (If you think about it, it makes sense, but as a beginner who had a working AppSync and just wanted to grant access to a Lambda, it wasn't that obvious what was wrong from the error message.)

**Comment by sidrubs** [comment]
@mciobanu Were you able to query the AppSync API from a Lambda using this method? Would you mind sharing your lambda code?

**Comment by mciobanu** [comment]
> 

@sidrubs  - Yes, I got it working, as mentioned in the post on February 6. I'm not sure you have the same problem that I had, as my issue was not with Lambda but with CDK and *cdk-appsync-transformer*.

For my issue, I didn't realize initially that not specifying authorization rules in *schema.graphql* would trigger *A PolicyStatement used in an identity-based policy must specify at least one resource*. The fix was to switch from
```
type DeviceHeartbeat @model @key(fields: ["deviceId", "time"]) {
  deviceId: String!
  time: String!
  info: String
}
```
to
```
type DeviceHeartbeat @model @key(fields: ["deviceId", "time"])  @aws_iam @aws_api_key @aws_cognito_user_pools @auth(rules: [
  { allow: private, provider: iam, operations: [create update delete read] },
  { allow: private, provider: userPools, operations: [create update delete read] }
]){
  deviceId: String!
  time: String!
  info: String
}
```
(Not all authorization forms are needed. I was just experimenting.)

If you question is actually about calling AppSync from Lambda, this is a completely different thing, which can be pretty painful if you read the wrong documentation. I could tell you what I'm doing, if it helps. Keep in mind that my code is in TypeScript.

**Comment by sidrubs** [comment]
Thank you for the responst @mciobanu . I think my issue is actually on the lambda function side. No matter the client libraries used I always get a `Unable to parse JWT token` error.

I created a minimal example for explanation below:

My initial schema authentication types is shown below. (I did try give it all the authorization methods as in your example, but the error in the lambda function was the same):

```
type Project
  @model
  @auth(
    rules: [
      { allow: owner }
      { allow: private, provider: iam, operations: [read] }
    ]
  ) {
  id: ID!
  title: String!
  description: String
}
```

The stack is defined as follows:

```ts
import * as cdk from "@aws-cdk/core";
import * as appsync from "@aws-cdk/aws-appsync";
import * as cognito from "@aws-cdk/aws-cognito";
import * as lambda from "@aws-cdk/aws-lambda";

import { AppSyncTransformer } from "cdk-appsync-transformer";

export class TempStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // A user pool stores the app users.
    const userPool = new cognito.UserPool(this, "UserPool", {
      selfSignUpEnabled: true,
      autoVerify: { email: true },
      signInAliases: { username: true },
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

    // The user pool client allows a web app to authenticate against the user pool.
    const userPoolClient = new cognito.UserPoolClient(this, "UserPoolClient", {
      userPool: userPool,
      generateSecret: false,
      supportedIdentityProviders: [
        cognito.UserPoolClientIdentityProvider.COGNITO,
      ],
      oAuth: {
        callbackUrls: ["http://localhost:3000"],
        logoutUrls: ["http://localhost:3000"],
      },
    });

    // Appsync transformer
    const appsyncTransformer = new AppSyncTransformer(
      this,
      "AppsyncTransformer",
      {
        schemaPath: "./graphql/schema.graphql",
        authorizationConfig: {
          defaultAuthorization: {
            authorizationType: appsync.AuthorizationType.USER_POOL,
            userPoolConfig: {
              userPool: userPool,
              appIdClientRegex: userPoolClient.userPoolClientId,
              defaultAction: appsync.UserPoolDefaultAction.ALLOW,
            },
          },
        },
      }
    );

    const identityPool = new cognito.CfnIdentityPool(this, "IdentityPool", {
      allowUnauthenticatedIdentities: true,
      cognitoIdentityProviders: [
        {
          clientId: userPoolClient.userPoolClientId,
          providerName: userPool.userPoolProviderName,
        },
      ],
    });

    // Create lambda function to make an IAM request
    const iamAccessLambda = new lambda.DockerImageFunction(
      this,
      `IamAccessLambdaFunction`,
      {
        code: lambda.DockerImageCode.fromImageAsset(
          "./containers/iamAccessLambda"
        ),
        currentVersionOptions: {
          removalPolicy: cdk.RemovalPolicy.DESTROY,
          retryAttempts: 1,
        },
        timeout: cdk.Duration.seconds(13),
        environment: {
          ENDPOINT: appsyncTransformer.appsyncAPI.graphqlUrl,
        },
      }
    );

    // Grant private access to Lambda function
    appsyncTransformer.grantPrivate(iamAccessLambda);

    // Create some outputs
    new cdk.CfnOutput(this, "Region", {
      value: this.region,
    });

    new cdk.CfnOutput(this, "AppsyncApiEndpoint", {
      value: appsyncTransformer.appsyncAPI.graphqlUrl,
    });

    new cdk.CfnOutput(this, "IdentityPoolId", {
      value: identityPool.ref,
    });

    new cdk.CfnOutput(this, "UserPoolId", {
      value: userPool.userPoolId,
    });

    new cdk.CfnOutput(this, "UserPoolClientId", {
      value: userPoolClient.userPoolClientId,
    });
  }
}
```
And my Lambda function is as follows (adapted from [here](https://stackoverflow.com/a/67269644)):

```js
const env = require("process").env;
const AWS = require("aws-sdk");
const { AWSAppSyncClient } = require("aws-appsync");
const gql = require("graphql-tag");
require("cross-fetch/polyfill");

// Set up the AWS sdk with the correct credentials
AWS.config.update({
  region: env.AWS_REGION,
  credentials: new AWS.Credentials(
    env.AWS_ACCESS_KEY_ID,
    env.AWS_SECRET_ACCESS_KEY,
    env.AWS_SESSION_TOKEN
  ),
});

const ENDPOINT = env.ENDPOINT;
const REGION = env.AWS_REGION;

// Check that the correct endpoint and region are coming through
console.log("Endpoint: ", ENDPOINT);
console.log("Region: ", REGION);

// The lambda handler
exports.handler = (event, context, callback) => {
  // A basic GraphQL query
  const ListProjects = gql`
    query ListProjects {
      listProjects {
        items {
          title
          owner
          id
        }
      }
    }
  `;

  // Create and Appsync client with auth type `AWS_IAM`
  const client = new AWSAppSyncClient({
    url: ENDPOINT,
    region: REGION,
    auth: {
      credentials: AWS.config.credentials,
      type: "AWS_IAM",
    },
    disableOffline: true,
  });

  console.log("Making request");

  return client.query({
    query: ListProjects,
    fetchPolicy: "no-cache",
  });
};
```
Looking at the configuration of the deployed Lambda I can see the role with permissions to access all the AppSync endpoints. I have tried many different methods for the lambda function ranging from the above, to using the Amplify client library, so pure http requests. I always get same error:

```json
{
    "errorType": "Error",
    "errorMessage": "Network error: Response not successful: Received status code 401",
    "graphQLErrors": [],
    "networkError": {
        "errorType": "ServerError",
        "errorMessage": "Response not successful: Received status code 401",
        "name": "ServerError",
        "response": {
            "size": 0,
            "timeout": 0
        },
        "statusCode": 401,
        "result": {
            "errors": [
                {
                    "errorType": "UnauthorizedException",
                    "message": "Unable to parse JWT token."
                }
            ]
        },
        "stack": [
            "ServerError: Response not successful: Received status code 401",
            "    at Object.exports.throwServerError (/var/task/node_modules/apollo-link-http-common/lib/index.js:23:17)",
            "    at /var/task/node_modules/apollo-link-http-common/lib/index.js:48:21",
            "    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
        ]
    },
    "message": "Network error: Response not successful: Received status code 401",
    "stack": [
        "Error: Network error: Response not successful: Received status code 401",
        "    at new ApolloError (/var/task/node_modules/apollo-client/bundle.umd.js:85:32)",
        "    at /var/task/node_modules/apollo-client/bundle.umd.js:1039:45",
        "    at /var/task/node_modules/apollo-client/bundle.umd.js:1411:21",
        "    at Array.forEach (<anonymous>)",
        "    at /var/task/node_modules/apollo-client/bundle.umd.js:1410:22",
        "    at Map.forEach (<anonymous>)",
        "    at QueryManager.broadcastQueries (/var/task/node_modules/apollo-client/bundle.umd.js:1405:26)",
        "    at /var/task/node_modules/apollo-client/bundle.umd.js:988:35",
        "    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
    ]
}
```

@mciobanu If you could point me in the direction of the "correct" documentation, or send a minimal example of your lambda function code this would be greatly appreciated.

**Comment by mciobanu** [comment]
@sidrubs - I wanted to make a sample project for a while, but I'm very busy and the relevant code is not so easy to disentangle from the rest. Anyway, one thing I would suggest is to test the parts separately, if you didn't do it already:
1. Make sure the endpoint can be called from the AppSync AWS console. (Note that this seemed to require you to define an API key, even if you don't plan to use it, which to me looks like a bug in the console.) You should be able to query items from the AWS console and switch between authorization protocols (I didn't play with IAM roles, only with IAM users and API Keys). So define first an API Key, to see how this part works. **Please note that you don't have everything from my example**: besides `@auth(...)`, there are also `@aws_iam`, `@aws_api_key`, `@aws_cognito_user_pools`. You might want to include all of them initially, and start removing what you don't need once you get things working.
2. Once the AppSync AWS console works, you can start worrying about the Lambda. Basically, the only thing needed in CDK is `appSyncTransformer.grantPrivate(yourFunction);`
3. Regarding the actual Lambda code, this was probably the trickiest for me, because I couldn't find any good examples. Initially I tried using what seemed to be the official AWS client, via `require('aws-appsync')`, which you also seem to use. I got it to work but it was very cumbersome due to old versions of various packages and the corresponding conflicts. What I use now is my own client (which will be refactored when time permits).

As I said, I don't have time to make a nice example, so I'll post a **partial** listing of my client, which I use from Lambdas (you'll need to tweak it to compile):
```typescript
import * as https from 'https';
import * as UrlParse from 'url';
const AWS = require('aws-sdk');

export interface AppSyncResponse<T> {
    data: T | undefined | null,
    errors: [{}] | undefined, // these don't get populated here, but in the execution of the HTTP promise
}

export interface AppSyncClient {
    request<T>(query: string, variables?: {}): Promise<AppSyncResponse<T>>;
}

class AppSyncClientImpl implements AppSyncClient {
    private readonly appsyncUrl: string;

    private readonly apiKey?: string;

    /**
     * @param {String} appsyncUrl url of your AppSync API
     * @param {String} apiKey the api key to include in headers. if null, will sign with SigV4
     */
    public constructor(appsyncUrl: string, apiKey?: string) {
        this.appsyncUrl = appsyncUrl;
        this.apiKey = apiKey;
        if (apiKey) {
            console.log('AppSyncClient: Using API Key');
        } else {
            const awsConfig = {
                region: process.env.AWS_REGION,
                credentials: new AWS.Credentials(
                        process.env.AWS_ACCESS_KEY_ID,
                        process.env.AWS_SECRET_ACCESS_KEY,
                        process.env.AWS_SESSION_TOKEN,
                ),
            };
            console.log(`AppSyncClient: Initialized AWS with ${debugFmt(awsConfig)}`);
            AWS.config.update(awsConfig);
        }
    }

    /**
     * Invokes a request (query or mutation)  //TODO: see about subscriptions
     *
     * @param query
     * @param variables - key-value
     */
    public async request<T>(query: string, variables?: {}): Promise<AppSyncResponse<T>> {
        const req = new AWS.HttpRequest(new AWS.Endpoint(this.appsyncUrl), process.env.AWS_REGION);
        const endpoint = new UrlParse.URL(this.appsyncUrl).hostname.toString();

        req.method = 'POST';
        req.path = '/graphql';
        req.headers.host = endpoint;
        req.headers['Content-Type'] = 'application/json';
        req.body = JSON.stringify({
            query,
            variables,
        });

        if (this.apiKey) {
            req.headers['x-api-key'] = this.apiKey;
        } else {
            const signer = new AWS.Signers.V4(req, 'appsync', true);
            signer.addAuthorization(AWS.config.credentials, AWS.util.date.getDate());
        }

        const promise = new Promise((resolve, reject) => {
            const httpRequest = https.request({...req, host: endpoint}, (result: any) => {
                result.on('data', (data: any) => {
                    resolve(JSON.parse(data.toString()));
                });
            });

            httpRequest.write(req.body);
            httpRequest.end();
        });

        const res = await promise.then((x) => x);
        return res as AppSyncResponse<T>;
    }
}
```
(If you pass an API Key, it will use it, otherwise it relies on environment variables.)

Then I use it something like this:
```typescript
import * as graphQlApi from './graphql/API';
import {AppSyncClient} from './AppSyncClient';
...
const appSyncClient = new AppSyncClientImpl(getAppSyncUrl(lambdaContext), process.env.APP_SYNC_KEY);
const getVariables: graphQlApi.GetDeviceQueryVariables = {
    deviceId,
};
const getDeviceResponse = await appSyncClient.request<graphQlApi.GetDeviceQuery>(queries.getDevice, getVariables);
```

**Comment by sidrubs** [comment]
@mciobanu thank you for your response. Telling me to get it to work in _AppSync AWS console_ is what got it working for me. I noticed that in the AppSync settings (in the console) there were no _Additional authorization providers_.

I solved this using [this](https://github.com/kcwinner/cdk-appsync-transformer/issues/369#issuecomment-1114760726) code except I altered the `AppSyncTransformer` as follows. Note the `additionalAuthorizationModes` section.

```ts
// Appsync transformer
const appsyncTransformer = new AppSyncTransformer(
  this,
  "AppsyncTransformer",
  {
    schemaPath: "./graphql/schema.graphql",
    authorizationConfig: {
      defaultAuthorization: {
        authorizationType: appsync.AuthorizationType.USER_POOL,
        userPoolConfig: {
          userPool: userPool,
          appIdClientRegex: userPoolClient.userPoolClientId,
          defaultAction: appsync.UserPoolDefaultAction.ALLOW,
        },
      },
      additionalAuthorizationModes: [
        {
          authorizationType: appsync.AuthorizationType.IAM,
        },
      ],
    },
  }
);
```

**Comment by mciobanu** [comment]
You're right, I also use `additionalAuthorizationModes`, but it was in a different location and I didn't notice it.
